import axios, { AxiosError, AxiosInstance, AxiosRequestConfig } from "axios";
import { refreshUser, logoutUser } from "./authClient";
import { apiUrl } from "../constants";

const api: AxiosInstance = axios.create({
    baseURL: apiUrl,
    withCredentials: true,
});

let isRefreshing = false;
let failedQueue: {
    resolve: (value?: unknown) => void;
    reject: (reason?: any) => void;
}[] = [];

function processQueue(error: any, token: any = null) {
    failedQueue.forEach((prom) => {
        if (error) prom.reject(error);
        else prom.resolve(token);
    });
    failedQueue = [];
}

api.interceptors.response.use(
    (response) => response,
    async (error: AxiosError) => {
        const originalRequest = error.config as AxiosRequestConfig & { _retry?: boolean };

        if (error.response?.status === 401 && !originalRequest._retry) {
            originalRequest._retry = true;

            if (isRefreshing) {
                return new Promise((resolve, reject) => {
                    failedQueue.push({
                        resolve: () => resolve(api(originalRequest)),
                        reject,
                    });
                });
            }

            isRefreshing = true;

            try {
                await refreshUser();
                processQueue(null);
                return api(originalRequest);
            } catch (err) {
                processQueue(err, null);
                await logoutUser();
                window.location.href = "/login";
                return Promise.reject(err);
            } finally {
                isRefreshing = false;
            }
        }

        return Promise.reject(error);
    }
);

export default api;
